periodics:

  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu1604-Release-c-7
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'        

  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu1604-Release-gcc
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'        

  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu1604-Debug-c-7
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'        

  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu1604-Debug-gcc
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu1804-Release-c-7
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'        

  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu1804-Release-gcc
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'        

  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu1804-Debug-c-7
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'        

  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu1804-Debug-gcc
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        
