periodics:
  - name: ci-oeedger8r-cpp-ubuntu-1604-Release-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h1m
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-8"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Release-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h2m
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-7"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Release-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h3m
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=gcc"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Debug-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h4m
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-8"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Debug-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h5m
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-7"

  - name: ci-oeedger8r-cpp-ubuntu-1604-Debug-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h6m
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=gcc"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Release-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h7m
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-8"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Release-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h8m
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=clang-7"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Release-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h9m
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Release --compiler=gcc"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Debug-clang-8
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h10m
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-8"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Debug-clang-7
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h11m
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=clang-7"

  - name: ci-oeedger8r-cpp-ubuntu-1804-Debug-gcc
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h12m
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - "-c"
            - "/testing/oeedger8r-cpp/cmake-build.sh -b=Debug --compiler=gcc"        

  - name: ci-oeedger8r-cpp-rhel-8-release
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h13m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master,OE_PULL_NUMBER=master,TEST_INFRA=false,BUILD_TYPE=Release"

  - name: ci-oeedger8r-rhel-8-debug
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h14m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master,OE_PULL_NUMBER=master,TEST_INFRA=false,BUILD_TYPE=Debug"

  - name: ci-oeedger8r-cpp-rhel-8-reldebinfo
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h15m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master,OE_PULL_NUMBER=master,TEST_INFRA=false,BUILD_TYPE=RelWithDebInfo"

  - name: ci-oeedger8r-cpp-win-2016-release
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h16m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/WindowsBuild --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master,OE_PULL_NUMBER=master,TEST_INFRA=false,WINDOWS_VERSION=2016,BUILD_TYPE=Release"

  - name: ci-oeedger8r-cpp-win-2016-debug
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h17m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/WindowsBuild --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master,OE_PULL_NUMBER=master,TEST_INFRA=false,WINDOWS_VERSION=2016,BUILD_TYPE=Debug"

  - name: ci-oeedger8r-cpp-win-2019-release
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h18m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/WindowsBuild --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master,OE_PULL_NUMBER=master,TEST_INFRA=false,WINDOWS_VERSION=2019,BUILD_TYPE=Release"

  - name: ci-oeedger8r-cpp-win-2019-debug
    extra_refs:
    - org: openenclave
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h19m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job oeedger8r-cpp/job/WindowsBuild --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master,OE_PULL_NUMBER=master,TEST_INFRA=false,WINDOWS_VERSION=2019,BUILD_TYPE=Debug"
