  - name: ci-${org}-${repo}-${operating_system}-${build_type_short}-${compiler_short}
    extra_refs:
    - org: ${org}
      repo: ${repo}
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/${operating_system}:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=${build_type} --compiler=${compiler}'
