presubmits:
  openenclave-ci/test-infra:
  - name: pr-openenclave-test-infra-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/jenkinsoperator:latest
        command:
        - /bin/bash
        args:
        - -c
        - "echo ping"

  - name: pr-openenclave-test-infra-validate-build-image-ubuntu-1804
    branches:
    - master
    run_if_changed: "^(images/ubuntu/1804/*)|(images/scripts/*)|(images/test/*)|(hack/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1804/Dockerfile --docker_tag openenclave/ubuntu-1804"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
            - mountPath: /dev/sgx
              name: dev-sgx
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

  - name: pr-openenclave-test-infra-validate-build-image-ubuntu-1604
    branches:
    - master
    run_if_changed: "^(images/ubuntu/1604/*)|(images/scripts/*)|(images/test/*)|(hack/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1804/Dockerfile --docker_tag openenclave/ubuntu-1604"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: pr-openenclave-test-infra-validate-build-image-bootstrap-did
    branches:
    - master
    run_if_changed: "^(images/bootstrap/*)|(images/scripts/*)|(images/test/*)|(hack/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "docker build . -f images/bootstap/Dockerfile"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: pr-openenclave-test-infra-validate-build-image-rhel-8.1
    branches:
    - master
    run_if_changed: "^(images/rhel/*)|(images/scripts/*)|(images/test/*)|(hack/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/rhel/8.1/Dockerfile --skip_testing --docker_tag openenclave/rhel-8.1"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: pr-openenclave-test-infra-validate-build-image-centos-7.5
    branches:
    - master
    run_if_changed: "^(images/centos/*)|(images/scripts/*)|(images/test/*)|(hack/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/centos/7.5/Dockerfile --skip_testing --docker_tag centos-7.5"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
            - mountPath: /dev/sgx
              name: dev-sgx
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

  - name: pr-openenclave-test-infra-validate-build-image-fedora-31
    branches:
    - master
    run_if_changed: "^(images/fedora/*)|(images/scripts/*)|(images/test/*)|(hack/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/fedora/31/Dockerfile --skip_testing --docker_tag fedora-31"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

# TO DO add job to launch a jenkins job 
  - name: pr-openenclave-test-infra-validate-build-image-jenkins-op
    branches:
    - master
    run_if_changed: "^(images/jenkinsoperator/*)|(images/scripts/*)|(images/test/*)|(hack/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/jenkinsoperator/Dockerfile --skip_testing --docker_tag jenkinsoperator"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev/sgx
              name: dev-sgx
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never

  - name: pr-openenclave-test-infra-jenkins-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/jenkins-ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN"

  - name: pr-openenclave-test-infra-validate-build-image-windows-2019
    branches:
    - master
    run_if_changed: "^(images/windows/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/Windows2019DockerBuild --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,TEST_INFRA=true"

  - name: pr-openenclave-test-infra-validate-oeedgrg8r-rhel-8
    branches:
    - master
    run_if_changed: "^(config/jobs/oeedger8r-cpp/jenkins/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Rhel8Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,TEST_INFRA=true"

  - name: pr-openenclave-test-infra-validate-oeedgrg8r-win-2016
    branches:
    - master
    run_if_changed: "^(config/jobs/oeedger8r-cpp/jenkins/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Windows2016Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,TEST_INFRA=true"

  - name: pr-openenclave-test-infra-validate-oeedgrg8r-win-2019
    branches:
    - master
    run_if_changed: "^(config/jobs/oeedger8r-cpp/jenkins/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER,TEST_INFRA=true"
