  - name: ci-${org}-${repo}-acc-${operating_system}-${build_type_short}-${compiler_short}
    extra_refs:
    - org: ${org}
      repo: ${repo}
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/${operating_system}:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=${build_type} --compiler=${compiler} --hardware_mode'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never
