  - name: pr-${org}-${repo}-acc-${operating_system}-${build_type}-${compiler_short}
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/${operating_system}:latest
          command:
          - /bin/bash
          args:
          - -c
          - '/hack/cmake-build.sh -b=${build_type} --compiler=${compiler}'
          volumeMounts:
          - mountPath: /dev/sgx
            name: dev-sgx
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      restartPolicy: Never
