presubmits:
  openenclave/openenclave-curl:

  - name: pr-openenclave-curl-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-curl/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-curl-Ubuntu1604BuildClang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-curl/job/Ubuntu1604BuildClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-curl-Ubuntu1804BuildClang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-curl/job/Ubuntu1804BuildClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        
