---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-nodeport
  labels:
    app: jenkins-master
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: slave
    port: 50000
    targetPort: 50000
    protocol: TCP
  selector:
    app: jenkins-master
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-master-volume
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=1000
- gid=1000
- mfsymlinks
- cache=strict
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-volume
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: jenkins-master-volume
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
spec:
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/configuration/
        - name: SECRET_JENKINSADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jenkinsadmin
              key: password
        - name: SECRET_OEADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oeadmin
              key: password
        - name: SECRET_JENKINS_REMOTE_TRIGGER_TOKEN
          valueFrom:
            secretKeyRef:
              name: jenkinsremotetrigger
              key: password
        - name: SECRET_AZURE_SERVICE_PRINCIPAL_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: jenkinssp
              key: clientid
        - name: SECRET_AZURE_SERVICE_PRINCIPAL_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: jenkinssp
              key: subscriptionid
        - name: SECRET_AZURE_SERVICE_PRINCIPAL_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: jenkinssp
              key: tenantid
        - name: SECRET_AZURE_SERVICE_PRINCIPAL_SECRET
          valueFrom:
            secretKeyRef:
              name: jenkinssp
              key: secret
        volumeMounts:
        - name: volume
          mountPath: "/var/jenkins_home"
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          failureThreshold: 10
          initialDelaySeconds: 1800
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /login
            port: 8080
          failureThreshold: 60
          periodSeconds: 30
        resources:
          requests:
            cpu: "2"
            memory: 8Gi
          limits:
            cpu: "8"
            memory: 30Gi
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: jenkins-master-volume
